spring.application.name=Nasir

spring.datasource.url=jdbc:postgresql://localhost:5432/nasir_db
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api

jwt.secret=nasir_super_secret_key_minimo_32_caracteres!!
jwt.expiration=86400000

tmdb.api.key=038e969f7734facdf034096f7fc9b8bd
tmdb.access.token=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIwMzhlOTY5Zjc3MzRmYWNkZjAzNDA5NmY3ZmM5YjhiZCIsIm5iZiI6MTc4MTIzMzYzOS44NjMwMDAyLCJzdWIiOiI2YTJiNzdlNzU5MzBjYTQyZTFlM2I5ZTUiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.r7bE3UhNSrESCA6yUOmH54oTsk9eMeiN4-NZRMlOvZw
tmdb.base.url=https://api.themoviedb.org/3
tmdb.image-base-url=https://image.tmdb.org/t/p/w500